import { NextRequest, NextResponse } from "next/server";

type CitationFormat = "apa" | "mla" | "chicago" | "none";

function formatCitation(finding: any, format: CitationFormat): string {
  const { title, url, retrieved_at } = finding.source;
  const date = new Date(retrieved_at);
  const accessedDate = date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const domain = new URL(url).hostname?.replace("www.", "") || "";

  switch (format) {
    case "apa":
      return `${domain}. (${date.getFullYear()}). ${title}. Retrieved ${accessedDate}, from ${url}`;
    case "mla":
      return `"${title}." ${domain}, ${date.getFullYear()}, ${url}. Accessed ${accessedDate}.`;
    case "chicago":
      return `${domain}. "${title}." Accessed ${accessedDate}. ${url}.`;
    default:
      return `${title} - ${url}`;
  }
}

function generateMarkdown(result: any, citationFormat: CitationFormat = "none"): string {
  let md = `# ${result.topic}\n\n`;
  md += `**Generated:** ${new Date().toLocaleString()}\n\n`;

  // For hybrid method, summary is the full formatted analysis
  if (result.method === "perplexity-claude" && result.summary) {
    md += result.summary + "\n\n";
  } else if (result.summary) {
    // For perplexity-only, show summary then findings
    md += `## Summary\n\n${result.summary}\n\n`;
    md += `## Key Findings\n\n`;
    result.findings.forEach((finding: any, i: number) => {
      md += `### ${i + 1}. Finding\n\n${finding.text}\n\n`;
      md += `- **Source:** [${finding.source.title}](${finding.source.url})\n`;
      md += `- **Domain:** ${finding.source.domain}\n\n`;
    });
  }

  if (citationFormat !== "none") {
    md += `## References\n\n`;
    result.findings.forEach((finding: any, i: number) => {
      md += `${i + 1}. ${formatCitation(finding, citationFormat)}\n\n`;
    });
  } else if (result.findings.length > 0 && result.findings[0].source.domain !== "anthropic.com") {
    // Only show sources section for perplexity-only (anthropic.com is placeholder for hybrid)
    md += `## Sources\n\n`;
    result.findings.forEach((finding: any, i: number) => {
      md += `${i + 1}. [${finding.source.title}](${finding.source.url})\n`;
      md += `   - Retrieved: ${new Date(finding.source.retrieved_at).toLocaleString()}\n\n`;
    });
  }

  md += `---\n*Generated by Research Pipeline*`;
  return md;
}

function generateWord(result: any, citationFormat: CitationFormat = "none"): string {
  let text = `${result.topic.toUpperCase()}\n\n`;
  text += `Generated: ${new Date().toLocaleString()}\n\n`;

  // For hybrid method, summary is the full formatted analysis
  if (result.method === "perplexity-claude" && result.summary) {
    text += result.summary + "\n\n";
  } else if (result.summary) {
    // For perplexity-only, show summary then findings
    text += `SUMMARY\n${result.summary}\n\n`;
    text += `KEY FINDINGS\n`;
    result.findings.forEach((finding: any, i: number) => {
      text += `\n${i + 1}. ${finding.text}\n`;
      text += `Source: ${finding.source.title} (${finding.source.domain})\n`;
      text += `URL: ${finding.source.url}\n`;
    });
  }

  if (citationFormat !== "none") {
    text += `\nREFERENCES\n`;
    result.findings.forEach((finding: any, i: number) => {
      text += `${i + 1}. ${formatCitation(finding, citationFormat)}\n\n`;
    });
  } else if (result.findings.length > 0 && result.findings[0].source.domain !== "anthropic.com") {
    text += `\nSOURCES\n`;
    result.findings.forEach((finding: any, i: number) => {
      text += `${i + 1}. ${finding.source.title}\n   URL: ${finding.source.url}\n`;
    });
  }

  return text;
}

function generatePdf(result: any, citationFormat: CitationFormat = "none"): string {
  // Generate HTML that will be converted to PDF on the client
  let findingsHtml = "";

  if (result.method === "perplexity-claude" && result.summary) {
    // For hybrid: render summary as formatted markdown/HTML
    findingsHtml = result.summary
      .replace(/^# /gm, "<h1>")
      .replace(/\n$/gm, "</h1>")
      .replace(/^## /gm, "<h2>")
      .replace(/\n$/gm, "</h2>")
      .replace(/^### /gm, "<h3>")
      .replace(/\n$/gm, "</h3>")
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.*?)\*/g, "<em>$1</em>")
      .replace(/\n\n/g, "</p><p>")
      .replace(/^\s*[-*]\s+/gm, "<li>")
      .replace(/\n/g, "</li><li>");
  } else {
    // For perplexity-only: show each finding
    findingsHtml = result.findings
      .map(
        (finding: any, i: number) => `
      <div class="finding">
        <h3>${i + 1}. Finding</h3>
        <p>${finding.text}</p>
        <p><strong>Source:</strong> <a class="source" href="${finding.source.url}">${finding.source.title}</a></p>
        <p><strong>Domain:</strong> ${finding.source.domain}</p>
      </div>
    `
      )
      .join("");
  }

  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${result.topic} - Research Report</title>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 850px; margin: 0 auto; padding: 20px; }
        h1 { color: #667eea; border-bottom: 2px solid #667eea; padding-bottom: 10px; margin-top: 30px; }
        h2 { color: #764ba2; margin-top: 25px; }
        h3 { color: #555; }
        .meta { background: #f5f5f5; padding: 10px; border-radius: 5px; margin-bottom: 20px; font-size: 0.95em; }
        .finding { background: #fafafa; padding: 15px; border-left: 4px solid #667eea; margin: 15px 0; }
        .source { color: #667eea; text-decoration: none; font-weight: 600; }
        .citation { margin: 10px 0; font-size: 0.95em; line-height: 1.5; }
        .page-break { page-break-after: always; }
        p { margin: 10px 0; }
      </style>
    </head>
    <body>
      <h1>${result.topic}</h1>
      <div class="meta">
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
        ${citationFormat !== "none" ? `<p><strong>Citation Format:</strong> ${citationFormat.toUpperCase()}</p>` : ""}
      </div>
      ${findingsHtml}
      ${citationFormat !== "none" && result.findings.length > 0 ? `<div class="page-break"></div><h2>References</h2>${result.findings.map((finding: any, i: number) => `<div class="citation">${i + 1}. ${formatCitation(finding, citationFormat)}</div>`).join("")}` : ""}
    </body>
    </html>
  `;
  return html;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { result, format, citationFormat } = body;

    if (!result || !format) {
      return NextResponse.json(
        { error: "Result and format are required" },
        { status: 400 }
      );
    }

    const citations: CitationFormat = (citationFormat as CitationFormat) || "none";

    let content: string;
    let contentType: string;
    let filename: string;

    if (format === "markdown") {
      content = generateMarkdown(result, citations);
      contentType = "text/markdown; charset=utf-8";
      filename = `${result.topic.replace(/\s+/g, "_")}.md`;
    } else if (format === "docx") {
      content = generateWord(result, citations);
      contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
      filename = `${result.topic.replace(/\s+/g, "_")}.docx`;
    } else if (format === "pdf") {
      content = generatePdf(result, citations);
      contentType = "text/html; charset=utf-8";
      filename = `${result.topic.replace(/\s+/g, "_")}.html`;
    } else {
      return NextResponse.json({ error: "Invalid format" }, { status: 400 });
    }

    return new NextResponse(content, {
      headers: {
        "Content-Type": contentType,
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
