import { NextRequest, NextResponse } from "next/server";

type CitationFormat = "apa" | "mla" | "chicago" | "none";

function formatCitation(finding: any, format: CitationFormat): string {
  const { title, url, retrieved_at } = finding.source;
  const date = new Date(retrieved_at);
  const accessedDate = date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const domain = new URL(url).hostname?.replace("www.", "") || "";

  switch (format) {
    case "apa":
      return `${domain}. (${date.getFullYear()}). ${title}. Retrieved ${accessedDate}, from ${url}`;
    case "mla":
      return `"${title}." ${domain}, ${date.getFullYear()}, ${url}. Accessed ${accessedDate}.`;
    case "chicago":
      return `${domain}. "${title}." Accessed ${accessedDate}. ${url}.`;
    default:
      return `${title} - ${url}`;
  }
}

function generateMarkdown(result: any, citationFormat: CitationFormat = "none"): string {
  let md = `# Research Report: ${result.topic}\n\n`;
  md += `**Generated:** ${new Date().toLocaleString()}\n`;
  md += `**Findings:** ${result.findings.length}\n`;
  if (citationFormat !== "none") {
    md += `**Citation Format:** ${citationFormat.toUpperCase()}\n`;
  }
  md += `\n`;

  if (result.summary) {
    md += `## Summary\n\n${result.summary}\n\n`;
  }

  md += `## Key Findings\n\n`;
  result.findings.forEach((finding: any, i: number) => {
    md += `### ${i + 1}. ${finding.text.substring(0, 80)}...\n\n`;
    md += `- **Source:** [${finding.source.title}](${finding.source.url})\n`;
    md += `- **Domain:** ${finding.source.domain}\n`;
    md += `- **Relevance:** ${(finding.scores.relevance * 100).toFixed(0)}%\n`;
    md += `- **Credibility:** ${(finding.scores.credibility * 100).toFixed(0)}%\n`;
    md += `- **Recency:** ${(finding.scores.recency * 100).toFixed(0)}%\n`;
    md += `- **Combined Score:** ${(finding.scores.combined * 100).toFixed(0)}%\n\n`;
  });

  if (citationFormat !== "none") {
    md += `## References\n\n`;
    result.findings.forEach((finding: any, i: number) => {
      md += `${i + 1}. ${formatCitation(finding, citationFormat)}\n\n`;
    });
  } else {
    md += `## All Sources\n\n`;
    result.findings.forEach((finding: any, i: number) => {
      md += `${i + 1}. [${finding.source.title}](${finding.source.url})\n`;
      md += `   - Retrieved: ${new Date(finding.source.retrieved_at).toLocaleString()}\n\n`;
    });
  }

  md += `---\n*Generated by Research Pipeline*`;
  return md;
}

function generateWord(result: any, citationFormat: CitationFormat = "none"): string {
  let text = `RESEARCH REPORT: ${result.topic}\n\n`;
  text += `Generated: ${new Date().toLocaleString()}\n`;
  text += `Findings: ${result.findings.length}\n`;
  if (citationFormat !== "none") {
    text += `Citation Format: ${citationFormat.toUpperCase()}\n`;
  }
  text += `\n`;

  if (result.summary) {
    text += `SUMMARY\n${result.summary}\n\n`;
  }

  text += `KEY FINDINGS\n`;
  result.findings.forEach((finding: any, i: number) => {
    text += `\n${i + 1}. ${finding.text}\n`;
    text += `Source: ${finding.source.title} (${finding.source.domain})\n`;
    text += `URL: ${finding.source.url}\n`;
    text += `Scores: Relevance ${(finding.scores.relevance * 100).toFixed(0)}% | `;
    text += `Credibility ${(finding.scores.credibility * 100).toFixed(0)}% | `;
    text += `Recency ${(finding.scores.recency * 100).toFixed(0)}% | `;
    text += `Combined ${(finding.scores.combined * 100).toFixed(0)}%\n`;
  });

  if (citationFormat !== "none") {
    text += `\nREFERENCES\n`;
    result.findings.forEach((finding: any, i: number) => {
      text += `${i + 1}. ${formatCitation(finding, citationFormat)}\n\n`;
    });
  } else {
    text += `\nSOURCES\n`;
    result.findings.forEach((finding: any, i: number) => {
      text += `${i + 1}. ${finding.source.title}\n   URL: ${finding.source.url}\n`;
    });
  }

  return text;
}

function generatePdf(result: any, citationFormat: CitationFormat = "none"): string {
  // Generate HTML that will be converted to PDF on the client
  let html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${result.topic} - Research Report</title>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 850px; margin: 0 auto; padding: 20px; }
        h1 { color: #667eea; border-bottom: 2px solid #667eea; padding-bottom: 10px; }
        h2 { color: #764ba2; margin-top: 30px; }
        h3 { color: #333; }
        .meta { background: #f5f5f5; padding: 10px; border-radius: 5px; margin-bottom: 20px; font-size: 0.95em; }
        .finding { background: #fafafa; padding: 15px; border-left: 4px solid #667eea; margin: 15px 0; }
        .scores { font-size: 0.9em; color: #666; }
        .source { color: #667eea; text-decoration: none; font-weight: 600; }
        .citation { margin: 10px 0; font-size: 0.95em; line-height: 1.5; }
        .page-break { page-break-after: always; }
      </style>
    </head>
    <body>
      <h1>Research Report: ${result.topic}</h1>
      <div class="meta">
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
        <p><strong>Findings:</strong> ${result.findings.length}</p>
        ${citationFormat !== "none" ? `<p><strong>Citation Format:</strong> ${citationFormat.toUpperCase()}</p>` : ""}
      </div>
      ${result.summary ? `<h2>Summary</h2><p>${result.summary}</p>` : ""}
      <h2>Key Findings</h2>
      ${result.findings
        .map(
          (finding: any, i: number) => `
        <div class="finding">
          <h3>${i + 1}. ${finding.text.substring(0, 100)}</h3>
          <p><strong>Source:</strong> <a class="source" href="${finding.source.url}">${finding.source.title}</a></p>
          <p><strong>Domain:</strong> ${finding.source.domain}</p>
          <div class="scores">
            <p>Relevance: ${(finding.scores.relevance * 100).toFixed(0)}% |
               Credibility: ${(finding.scores.credibility * 100).toFixed(0)}% |
               Recency: ${(finding.scores.recency * 100).toFixed(0)}% |
               Combined: ${(finding.scores.combined * 100).toFixed(0)}%</p>
          </div>
        </div>
      `
        )
        .join("")}
      ${citationFormat !== "none" ? `<div class="page-break"></div><h2>References</h2>${result.findings.map((finding: any, i: number) => `<div class="citation">${i + 1}. ${formatCitation(finding, citationFormat)}</div>`).join("")}` : ""}
    </body>
    </html>
  `;
  return html;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { result, format, citationFormat } = body;

    if (!result || !format) {
      return NextResponse.json(
        { error: "Result and format are required" },
        { status: 400 }
      );
    }

    const citations: CitationFormat = (citationFormat as CitationFormat) || "none";

    let content: string;
    let contentType: string;
    let filename: string;

    if (format === "markdown") {
      content = generateMarkdown(result, citations);
      contentType = "text/markdown; charset=utf-8";
      filename = `${result.topic.replace(/\s+/g, "_")}.md`;
    } else if (format === "docx") {
      content = generateWord(result, citations);
      contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
      filename = `${result.topic.replace(/\s+/g, "_")}.docx`;
    } else if (format === "pdf") {
      content = generatePdf(result, citations);
      contentType = "text/html; charset=utf-8";
      filename = `${result.topic.replace(/\s+/g, "_")}.html`;
    } else {
      return NextResponse.json({ error: "Invalid format" }, { status: 400 });
    }

    return new NextResponse(content, {
      headers: {
        "Content-Type": contentType,
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
