"""Word document report generator."""

from pathlib import Path
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

from research_pipeline.reporters.base import BaseReporter
from research_pipeline.models import Research


class DocxReporter(BaseReporter):
    """Generates research reports in Word (.docx) format."""

    async def generate(self, research: Research, output_path: Path) -> Path:
        """Generate Word report and save to file."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        doc = self._build_docx(research)
        doc.save(str(output_path))
        return output_path

    @staticmethod
    def _build_docx(research: Research) -> Document:
        """Build Word document from research data."""
        doc = Document()

        # Title
        title = doc.add_heading(f"Research Report: {research.topic}", level=1)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Metadata
        meta = doc.add_paragraph()
        meta.add_run("Generated: ").bold = True
        meta.add_run(research.created_at.strftime("%Y-%m-%d %H:%M:%S"))
        meta.add_run(f" | Findings: {len(research.findings)}")

        # Summary
        if research.summary:
            doc.add_heading("Summary", level=2)
            doc.add_paragraph(research.summary)

        # Key Findings
        if research.findings:
            doc.add_heading("Key Findings", level=2)

            for i, finding in enumerate(research.findings, 1):
                # Finding heading
                heading = doc.add_heading(f"{i}. {finding.text[:80]}...", level=3)

                # Finding details table
                table = doc.add_table(rows=5, cols=2)
                table.style = "Light Grid Accent 1"

                cells = table.rows
                cells[0].cells[0].text = "Text"
                cells[0].cells[1].text = finding.text
                cells[1].cells[0].text = "Source"
                cells[1].cells[1].text = f"{finding.source.title} ({finding.source.domain})"
                cells[2].cells[0].text = "URL"
                cells[2].cells[1].text = finding.source.url
                cells[3].cells[0].text = "Retrieved"
                cells[3].cells[1].text = finding.source.retrieved_at.strftime("%Y-%m-%d %H:%M")

                # Scores row
                cells[4].cells[0].text = "Scores"
                scores_text = (
                    f"Relevance: {finding.relevance_score:.1%} | "
                    f"Credibility: {finding.credibility_score:.1%} | "
                    f"Recency: {finding.recency_score:.1%} | "
                    f"Combined: {finding.combined_score:.1%}"
                )
                cells[4].cells[1].text = scores_text

        # Knowledge Base Insights
        if research.knowledge_base_insights:
            doc.add_heading("Related Knowledge Base Insights", level=2)
            for insight in research.knowledge_base_insights:
                doc.add_paragraph(insight, style="List Bullet")

        # Sources
        if research.findings:
            doc.add_heading("All Sources", level=2)
            for i, finding in enumerate(research.findings, 1):
                para = doc.add_paragraph()
                para.add_run(f"{i}. ").bold = True
                para.add_run(finding.source.title)
                para.add_run(f" ({finding.source.domain})")
                sub = doc.add_paragraph(
                    f"Retrieved: {finding.source.retrieved_at.strftime('%Y-%m-%d %H:%M')}",
                    style="List Number"
                )
                sub.paragraph_format.left_indent = Inches(0.5)

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph("Generated by Research Pipeline")
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_format = footer.runs[0].font
        footer_format.size = Pt(9)
        footer_format.italic = True

        return doc
