"""Markdown report generator."""

from pathlib import Path
from research_pipeline.reporters.base import BaseReporter
from research_pipeline.models import Research


class MarkdownReporter(BaseReporter):
    """Generates research reports in Markdown format."""

    async def generate(self, research: Research, output_path: Path) -> Path:
        """Generate Markdown report and save to file."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        markdown = self._build_markdown(research)
        output_path.write_text(markdown, encoding="utf-8")
        return output_path

    @staticmethod
    def _build_markdown(research: Research) -> str:
        """Build Markdown report from research data."""
        lines = []

        # Title
        lines.append(f"# Research Report: {research.topic}\n")

        # Metadata
        lines.append(f"**Generated:** {research.created_at.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"**Findings:** {len(research.findings)}\n")

        # Summary
        if research.summary:
            lines.append("## Summary\n")
            lines.append(f"{research.summary}\n")

        # Key Findings
        if research.findings:
            lines.append("## Key Findings\n")
            for i, finding in enumerate(research.findings, 1):
                lines.append(f"### {i}. {finding.text[:80]}...\n")
                lines.append(f"- **Source:** [{finding.source.title}]({finding.source.url})")
                lines.append(f"- **Domain:** {finding.source.domain}")
                lines.append(f"- **Scores:**")
                lines.append(f"  - Relevance: {finding.relevance_score:.1%}")
                lines.append(f"  - Credibility: {finding.credibility_score:.1%}")
                lines.append(f"  - Recency: {finding.recency_score:.1%}")
                lines.append(f"  - **Combined:** {finding.combined_score:.1%}\n")

        # Knowledge Base Insights
        if research.knowledge_base_insights:
            lines.append("## Related Knowledge Base Insights\n")
            for insight in research.knowledge_base_insights:
                lines.append(f"- {insight}\n")

        # Sources
        if research.findings:
            lines.append("## All Sources\n")
            for i, finding in enumerate(research.findings, 1):
                lines.append(f"{i}. [{finding.source.title}]({finding.source.url})")
                lines.append(f"   - Retrieved: {finding.source.retrieved_at.strftime('%Y-%m-%d %H:%M')}\n")

        # Footer
        lines.append("---\n")
        lines.append("*Generated by Research Pipeline*")

        return "\n".join(lines)
